src/Entity/Pack.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PackRepository")
 */
class Pack
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Service", mappedBy="pack")
     */
    private $services;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Actif;


    public function __construct()
    {
      
        $this->services = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

  


    /**
     * @return Collection|Service[]
     */
    public function getServices(): Collection
    {
        return $this->services;
    }

    public function addService(Service $service): self
    {
        if (!$this->services->contains($service)) {
            $this->services[] = $service;
            $service->setPack($this);
        }

        return $this;
    }

    public function removeService(Service $service): self
    {
        if ($this->services->contains($service)) {
            $this->services->removeElement($service);
            // set the owning side to null (unless already changed)
            if ($service->getPack() === $this) {
                $service->setPack(null);
            }
        }

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->Actif;
    }

    public function setActif(bool $Actif): self
    {
        $this->Actif = $Actif;

        return $this;
    }
}

templates/packEtService/choixDesService.html.twig
{% extends "fragment/_navbar.html.twig" %}



{% block content %}
<div class="py-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <table class="table table-striped">
          <thead class="thead-dark">
            <left>
              <h2>Vos Services</h2>
            </left>
            <br>
            <br>
            <tr>
              <th scope="col">Nom des services choisies</th>
              <th scope="col">nombres de droits des services</th>
              <th scope="col">nombres de droits du service utilisé</th>
              <th scope="col">utiliser un service</th>
              <th scope="col">enlever ce service</th>
            </tr>
          </thead>
          <tbody>
            <h5>Vous pouvez utilisez chaque service une fois par jour</h5>
            {% for leServiceDuUser in lesServicesDuUser %}
            <tr>
              <td>{{ leServiceDuUser.service.nom }}</td>
              <td>{{ leServiceDuUser.service.nbDroit }}</td>
              <td>{{ leServiceDuUser.nbDroitUtiliser }}</td>

              {% if leServiceDuUser.statutDuServiceDuUser== 1 %}
              <td><a href="#" class="btn btn-success disabled" role="button" aria-disabled="true">ce service est
                  utilisé</a>
              </td>
              {% else %}
              <td><a class="btn btn-success" href={{path('ceService', {'idServiceDuUser': leServiceDuUser.id})}}>
                  utiliser ce service</a></td>

              <td><a href={{path('deleteService', {'idServicesDuUser': leServiceDuUser.id})}}
                  class="btn btn-danger">enlever ce service</a></td>
              {% endif %}
              <td></td>
            </tr>

            {% endfor %}
          </tbody>
        </table>
        <br>
        <left><a href={{ path('listeServiceSansPack',{'idPack':idPack}) }} class="btn btn-primary">ajouter un autre
            service</a></left>

        <div class=pull-right><a href={{ path('home') }} class="btn btn-primary">retour à l'accueil</a></div>
        {# grosse condition #}
      
       
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/packEtService/choixDuUser.html.twig
{% extends "fragment/_navbar.html.twig" %}



{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

               
                <h3>Vous avez payé vous pouvez réutiliser le service</h3>
                <br>
                <br>
               
              
              
             
            
                <div class=pull-right><a href={{ path('vosServices') }} class="btn btn-primary">retour à vos services</a></div>
              
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/packEtService/listePack.html.twig
{% extends "fragment/_navbar.html.twig" %}



{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if limiteServiceSALARIE == 0 %}
                {% if limiteServiceCADRE == 0 %}
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <th>Nom des packs</th>
                            <th>Voir ces services</th>
                            <th>choisir un pack </th>
                        </tr>
                    <tbody>
                        {% for lePack in lesPacks %}
                        {% if lePack.id!=11 %}
                        <tr>

                            <td>{{ lePack.nom }} </td>
                            <td> </td>
                            {% if lePack.actif == 1 %}
                            <td><a href="#" class="btn btn-primary disabled" role="button" aria-disabled="true">choisir
                                    les services de ce pack</a>
                                <br>
                                <small>ce pack est déjà réserver</small>
                            </td>
                            <br>


                            {% else %}
                            <td> <a href={{ path('listeServiceAvecPack', {'idPack': lePack.id })  }}
                                    class="btn btn-primary">choisir ce pack</a></td>
                            {% endif  %}



                        </tr>
                        {% endif %}
                        {% endfor %}
                        {% else %}
                        <h3>vous avez atteint la limite du nombre de service pour un cadre qui est de 10 services</h3>
                        <br>
                        <a href={{ path('vosServices') }}
                            class="btn btn-primary">retour à vos services</a>
                        &nbsp;
                        {% endif %}

                        {% else %}
                        <h3>vous avez atteint la limite du nombre de service pour un salarier qui est de 5 services</h3>
                        <br>
                        <a href={{ path('vosServices') }}
                            class="btn btn-primary">retour à vos services</a>
                        &nbsp;
                        {% endif %}
                        </thead>
                    </tbody>
                </table>
                <a href={{ path('home') }} class="btn btn-primary">retour à l'accueil</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/packEtService/listeService.html.twig
{% extends "fragment/_navbar.html.twig" %}



{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                    {% if limiteServiceSALARIE == 0 %}
                    {% if limiteServiceCADRE == 0 %}
                <table class="table table-striped">
                    <thead class="thead-dark">

                        <tr>
                            <th scope="col">Nom des services</th>
                            <th scope="col">nombres de droits du service</th>
                            <th scope="col">Choisir ce service</th>
                        </tr>


                    <tbody>{# si #}
                      
                        {% for leService in lesServices %}

                        <tr>
                            <td>{{ leService.nom }}</td>
                            <td>{{ leService.nbDroit }}</td>
                            {#verifie si le user à deja choisi le service#}
                         
                            {% if leService.actif== 1 %}
                            <td><a href={{ path('choixDuService', {'idService': leService.id}) }}
                                class="btn btn-primary disabled"
                                role="button" aria-disabled="true">choisir ce service</a>
                                <br>
                                 <small>ce service est réservé</small>
                            </td>                              
                              {% else %}
                                 <td><a href={{ path('choixDuService', {'idService': leService.id}) }}
                                        class="btn btn-primary">choisir ce service</a></td>
                                 {% endif  %}  
                        </tr>             
                        {% endfor %} 

                        {% else %}
                        <h3>vous avez atteint la limite du nombre de service pour un cadre qui est de 10 services</h3>             
                        <a href={{ path('vosServices') }} class="btn btn-primary">retour à vos services</a>
                        &nbsp;
                        {% endif %}
                        
                        {% else %}
                        <h3>vous avez atteint la limite du nombre de service pour un salarier qui est de 5 services</h3>
                        <a href={{ path('vosServices') }} class="btn btn-primary">retour à vos services</a>
                        &nbsp;
                        {% endif %}      
                        </thead>
                    </tbody>
                </table>
                <a href={{ path('home') }} class="btn btn-primary">retour à l'accueil</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/packEtService/listeServiceAvecPack.html.twig
{% extends "fragment/_navbar.html.twig" %}



{% block content %}
<div class="py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table class="table table-striped">
                    <thead class="thead-dark">

                        <tr>
                            <th scope="col">Nom des services</th>
                            <th scope="col">nombres de droits du service</th>
                            <th scope="col">Choisir ce service</th>
                        </tr>

                    </thead>
                    <tbody>
                        {% for leService in lesServices %}

                        <tr>
                            <td>{{ leService.nom }}</td>
                            <td>{{ leService.nbDroit }}</td>
                            {#verifie si le user à deja choisi le service#}
                        </tr>
                        {% endfor %}
                </table>
                <br>
                <br>
                <a href={{ path('choixDuPack', {'idPack': packId}) }}
                        class="btn btn-primary">choisir les services de ce pack</a>
                </tbody>

                
                <div class="pull-right"><a href={{ path('listePack') }} class="btn btn-primary">retour à la liste des packs</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/packEtService/payerOuEnlever.html.twig
{% extends "fragment/_navbar.html.twig" %}



{% block content %}
<div class="py-5">
    <div class="container">
        {# grosse condition #}
        {% for leServiceDuUser in lesServicesDuUserDepasse %}

        <h3>Vous avez dépasser le nombre maximal d'utilisation du service {{  leServiceDuUser.service.nom }}</h3>
        <h3> soit vous enlever le service soit vous payer 100€</h3>
        <br>
        
        <a href={{path('attentionChoix')}} class="btn btn-primary">payer pour utiliser encore une fois le
            service</a>
         &nbsp;
        <a href={{path('deleteService', {'idServicesDuUser': leServiceDuUser.id})}} class="btn btn-danger">enlever
            ce service</a>
        {% endfor %}
    </div>
</div>
{% endblock %}